//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Motos_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Facturas()
        {
            this.Tbl_Detalles_Facturas = new HashSet<Tbl_Detalles_Facturas>();
        }
    
        public string id_Factura { get; set; }
        public string id_Cliente { get; set; }
        public string id_Tipo_Pago { get; set; }
        public System.DateTime fac_Fecha { get; set; }
    
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Detalles_Facturas> Tbl_Detalles_Facturas { get; set; }
        public virtual Tbl_Tipo_Pago Tbl_Tipo_Pago { get; set; }
    }
}
