//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Motos_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Detalles_Facturas
    {
        public string id_Detalle { get; set; }
        public string id_Factura { get; set; }
        public string id_Moto { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal flete_Envio { get; set; }
        public decimal impuesto_Aduana { get; set; }
        public decimal ganancia_Empresa { get; set; }
        public decimal impuesto_Venta { get; set; }
        public decimal descuento { get; set; }
        public decimal monto_Final { get; set; }
        public decimal monto_Dolares { get; set; }
    
        public virtual Tbl_Facturas Tbl_Facturas { get; set; }
        public virtual Tbl_Motos Tbl_Motos { get; set; }
    }
}
