//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Motos_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Motos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Motos()
        {
            this.Tbl_Ventas = new HashSet<Tbl_Ventas>();
        }
    
        public string id_Moto { get; set; }
        public string tipo { get; set; }
        public string marca { get; set; }
        public string descripcion { get; set; }
        public decimal precio_fabrica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Ventas> Tbl_Ventas { get; set; }
    }
}
