//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Motos_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ventas
    {
        public string id_Venta { get; set; }
        public string id_Cliente { get; set; }
        public string id_tipo_pago { get; set; }
        public string id_Moto { get; set; }
        public int cantidad { get; set; }
        public decimal flete_envio { get; set; }
        public decimal impuesto_aduana { get; set; }
        public decimal ganancia_empresa { get; set; }
        public decimal impuesto_venta { get; set; }
        public decimal descuento { get; set; }
        public decimal monto_final { get; set; }
        public decimal monto_dolares { get; set; }
    
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        public virtual Tbl_Motos Tbl_Motos { get; set; }
        public virtual Tbl_Tipo_Pago Tbl_Tipo_Pago { get; set; }
    }
}
